### ISSUE TITLE
Exporter crashes when SQL Server unavailable

### ISSUE THREAD

**Issue by vladvasiliu** [awaragi/prometheus-mssql-exporter#10]
Hello,

I'm having the following issue with the exporter : when the SQL Server instance is unavailable for a while, after a timeout, the exporter crashes.

Below are the logs:

````
Jul  6 15:17:08 prometheus-a prometheus-mssql-exporter[1308]: Failed to connect to database: Failed to connect to x.x.x.x:1433 in 15000ms
Jul  6 15:17:23 prometheus-a prometheus-mssql-exporter[1308]: Failed to connect to database: Failed to connect to x.x.x.x:1433 in 15000ms
Jul  6 15:17:39 prometheus-a prometheus-mssql-exporter[1308]: events.js:182
Jul  6 15:17:39 prometheus-a prometheus-mssql-exporter[1308]:       throw er; // Unhandled 'error' event
Jul  6 15:17:39 prometheus-a prometheus-mssql-exporter[1308]:       ^
Jul  6 15:17:39 prometheus-a prometheus-mssql-exporter[1308]:
Jul  6 15:17:39 prometheus-a prometheus-mssql-exporter[1308]: Error: No event 'socketConnect' in state 'Final'
Jul  6 15:17:39 prometheus-a prometheus-mssql-exporter[1308]:     at Connection.dispatchEvent (/usr/src/app/node_modules/tedious/lib/connection.js:689:28)
Jul  6 15:17:39 prometheus-a prometheus-mssql-exporter[1308]:     at Connection.socketConnect (/usr/src/app/node_modules/tedious/lib/connection.js:713:19)
Jul  6 15:17:39 prometheus-a prometheus-mssql-exporter[1308]:     at /usr/src/app/node_modules/tedious/lib/connection.js:606:16
Jul  6 15:17:39 prometheus-a prometheus-mssql-exporter[1308]:     at Socket.onConnect (/usr/src/app/node_modules/tedious/lib/connector.js:55:9)
Jul  6 15:17:39 prometheus-a prometheus-mssql-exporter[1308]:     at emitNone (events.js:105:13)
Jul  6 15:17:39 prometheus-a prometheus-mssql-exporter[1308]:     at Socket.emit (events.js:207:7)
Jul  6 15:17:39 prometheus-a prometheus-mssql-exporter[1308]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1140:10)
````

Host configuration:

````
prometheus-a :: ~ » lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

prometheus-a :: ~ » docker --version
Docker version 18.03.1-ce, build 9ee9f40
````

I'm running the container via `awaragi/prometheus-mssql-exporter:latest`

SQL Server is version 2016.

**Comment by awaragi** [comment]
As mentioned by @cobolbaby, Same as https://github.com/awaragi/prometheus-mssql-exporter/issues/10

The bug https://github.com/tediousjs/tedious/issues/782 should be fixed in the latest release.

**Comment by awaragi** [comment]
Tedious has been updated in version 1.1
