### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by soumen1102** [awaragi/prometheus-mssql-exporter#12]
Hi ,

Is there a compatible Grafana dashboard which can be used ?

Thanks,
Soumen

**Comment by ohad24** [comment]
join to question

**Comment by XIEBBS** [comment]
Join to the question.

**Comment by chpiter** [comment]
+1

**Comment by DiogoPeres** [comment]
join to question

**Comment by InchIK** [comment]
+1

**Comment by DiogoPeres** [comment]
Hello, I've made a simple grafana dashboard to show the metrics from prometheus-mssql-exporter, hope it helps. The link is the following: 
https://grafana.com/dashboards/9336

**Comment by cobolbaby** [comment]
https://grafana.com/grafana/dashboards/13919

**Comment by yansongwel** [comment]
[root@localhost prometheus]# docker run -e SERVER=172.17.12.70 -e USERNAME=sa -e PASSWORD='beta1xx#' -e PORT=1433 -e DEBUG=app -p 4000:4000 --name prometheus-mssql-exporter awaragi/prometheus-mssql-exporter
/usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint prometheus-mssql-exporter (fb921472c4a8456a8a8c000d8aaa1d1aea79f53467b18cf63a0fe941386420c1):  (iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.18.0.2 --dport 4000 -j ACCEPT: iptables: No chain/target/match by that name.
 (exit status 1)).

**Comment by yansongwel** [comment]
Thu, 04 Nov 2021 02:09:29 GMT app Connected to database
Error executing SQL query SELECT cntr_value
FROM sys.dm_os_performance_counters
where counter_name = 'Errors/sec' AND instance_name = 'User Errors' { RequestError: Timeout: Request failed to complete in 15000ms
    at RequestError (/usr/src/app/node_modules/tedious/lib/errors.js:34:12)
    at Connection.message (/usr/src/app/node_modules/tedious/lib/connection.js:1431:40)
    at Connection.dispatchEvent (/usr/src/app/node_modules/tedious/lib/connection.js:687:45)
    at MessageIO.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:602:18)
    at emitNone (events.js:105:13)
    at MessageIO.emit (events.js:207:7)
    at ReadablePacketStream.<anonymous> (/usr/src/app/node_modules/tedious/lib/message-io.js:102:16)
    at emitOne (events.js:115:13)
    at ReadablePacketStream.emit (events.js:210:7)
    at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:291:12)
  message: 'Timeout: Request failed to complete in 15000ms',
  code: 'ETIMEOUT' }
Thu, 04 Nov 2021 02:09:29 GMT app Connecting to database 172.17.12.70
Thu, 04 Nov 2021 02:09:30 GMT app Connecting to database 172.17.12.70
Thu, 04 Nov 2021 02:09:30 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:31 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:32 GMT app Connecting to database 172.17.12.70
Thu, 04 Nov 2021 02:09:33 GMT app Connected to database
Thu, 04 Nov 2021 02:09:34 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:34 GMT app Connected to database
Thu, 04 Nov 2021 02:09:34 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:34 GMT app Connecting to database 172.17.12.70
Thu, 04 Nov 2021 02:09:35 GMT app Connecting to database 172.17.12.70
Error executing SQL query SELECT TOP 1 cntr_value
FROM sys.dm_os_performance_counters where counter_name = 'Batch Requests/sec' { RequestError: Timeout: Request failed to complete in 15000ms
    at RequestError (/usr/src/app/node_modules/tedious/lib/errors.js:34:12)
    at Connection.message (/usr/src/app/node_modules/tedious/lib/connection.js:1431:40)
    at Connection.dispatchEvent (/usr/src/app/node_modules/tedious/lib/connection.js:687:45)
    at MessageIO.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:602:18)
    at emitNone (events.js:105:13)
    at MessageIO.emit (events.js:207:7)
    at ReadablePacketStream.<anonymous> (/usr/src/app/node_modules/tedious/lib/message-io.js:102:16)
    at emitOne (events.js:115:13)
    at ReadablePacketStream.emit (events.js:210:7)
    at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:291:12)
  message: 'Timeout: Request failed to complete in 15000ms',
  code: 'ETIMEOUT' }
Thu, 04 Nov 2021 02:09:35 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:35 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:36 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:36 GMT app Connected to database
Thu, 04 Nov 2021 02:09:37 GMT app Connected to database
Thu, 04 Nov 2021 02:09:37 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:37 GMT app Connecting to database 172.17.12.70
Error executing SQL query SELECT
cast(DB_Name(a.database_id) as varchar) as name,
    max(io_stall_read_ms),
    max(io_stall_write_ms),
    max(io_stall),
    max(io_stall_queued_read_ms),
    max(io_stall_queued_write_ms)
FROM
sys.dm_io_virtual_file_stats(null, null) a
INNER JOIN sys.master_files b ON a.database_id = b.database_id and a.file_id = b.file_id
group by a.database_id { RequestError: Timeout: Request failed to complete in 15000ms
    at RequestError (/usr/src/app/node_modules/tedious/lib/errors.js:34:12)
    at Connection.message (/usr/src/app/node_modules/tedious/lib/connection.js:1431:40)
    at Connection.dispatchEvent (/usr/src/app/node_modules/tedious/lib/connection.js:687:45)
    at MessageIO.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:602:18)
    at emitNone (events.js:105:13)
    at MessageIO.emit (events.js:207:7)
    at ReadablePacketStream.<anonymous> (/usr/src/app/node_modules/tedious/lib/message-io.js:102:16)
    at emitOne (events.js:115:13)
    at ReadablePacketStream.emit (events.js:210:7)
    at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:291:12)
  message: 'Timeout: Request failed to complete in 15000ms',
  code: 'ETIMEOUT' }
Thu, 04 Nov 2021 02:09:38 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:39 GMT app Connected to database
Thu, 04 Nov 2021 02:09:39 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:39 GMT app Connecting to database 172.17.12.70
Thu, 04 Nov 2021 02:09:40 GMT app Connecting to database 172.17.12.70
Failed to connect to database: Failed to connect to 172.17.12.70:1433 in 15000ms
Thu, 04 Nov 2021 02:09:40 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:41 GMT app Connected to database
Thu, 04 Nov 2021 02:09:41 GMT app Connected to database
Thu, 04 Nov 2021 02:09:42 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:42 GMT app Connecting to database 172.17.12.70
Thu, 04 Nov 2021 02:09:43 GMT app Connected to database
Thu, 04 Nov 2021 02:09:44 GMT app Connecting to database 172.17.12.70
Thu, 04 Nov 2021 02:09:45 GMT app Connected to database
Thu, 04 Nov 2021 02:09:45 GMT app Connecting to database 172.17.12.70
Error executing SQL query SELECT
cast(DB_Name(a.database_id) as varchar) as name,
    max(io_stall_read_ms),
    max(io_stall_write_ms),
    max(io_stall),
    max(io_stall_queued_read_ms),
    max(io_stall_queued_write_ms)
FROM
sys.dm_io_virtual_file_stats(null, null) a
INNER JOIN sys.master_files b ON a.database_id = b.database_id and a.file_id = b.file_id
group by a.database_id { RequestError: Timeout: Request failed to complete in 15000ms
    at RequestError (/usr/src/app/node_modules/tedious/lib/errors.js:34:12)
    at Connection.message (/usr/src/app/node_modules/tedious/lib/connection.js:1431:40)
    at Connection.dispatchEvent (/usr/src/app/node_modules/tedious/lib/connection.js:687:45)
    at MessageIO.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:602:18)
    at emitNone (events.js:105:13)
    at MessageIO.emit (events.js:207:7)
    at ReadablePacketStream.<anonymous> (/usr/src/app/node_modules/tedious/lib/message-io.js:102:16)
    at emitOne (events.js:115:13)
    at ReadablePacketStream.emit (events.js:210:7)
    at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:291:12)
  message: 'Timeout: Request failed to complete in 15000ms',
  code: 'ETIMEOUT' }
Thu, 04 Nov 2021 02:09:46 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:47 GMT app Connected to database
Thu, 04 Nov 2021 02:09:47 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:47 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:47 GMT app Connecting to database 172.17.12.70
Thu, 04 Nov 2021 02:09:48 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:49 GMT app Connecting to database 172.17.12.70
Thu, 04 Nov 2021 02:09:50 GMT app Connecting to database 172.17.12.70
Thu, 04 Nov 2021 02:09:51 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:52 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:52 GMT app Connected to database
Thu, 04 Nov 2021 02:09:52 GMT app Connecting to database 172.17.12.70
Thu, 04 Nov 2021 02:09:53 GMT app Connection to database ended
Thu, 04 Nov 2021 02:09:54 GMT app Connected to database
Thu, 04 Nov 2021 02:09:54 GMT app Connecting to database 172.17.12.70
Thu, 04 Nov 2021 02:09:55 GMT app Connecting to database 172.17.12.70
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: No event 'socketConnect' in state 'Final'
    at Connection.dispatchEvent (/usr/src/app/node_modules/tedious/lib/connection.js:689:28)
    at Connection.socketConnect (/usr/src/app/node_modules/tedious/lib/connection.js:713:19)
    at /usr/src/app/node_modules/tedious/lib/connection.js:606:16
    at Socket.onConnect (/usr/src/app/node_modules/tedious/lib/connector.js:55:9)
    at emitNone (events.js:105:13)
    at Socket.emit (events.js:207:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1140:10)
[root@k8s-svr-node4 dockerfile]#

**Comment by awaragi** [comment]
I have added Grafana dashboard suggestions to the readme (part of 1.1 to be released shortly). As for the error above, I only see network timeouts so unable to give more help on that.
