### ISSUE TITLE
Some errors on run

### ISSUE THREAD

**Issue by marcusramberg** [awaragi/prometheus-mssql-exporter#2]
Was able to start and auth with this using the docker container, but got a warning and an error that I thought I'd report:

```
(node:1) [DEP0064] DeprecationWarning: tls.createSecurePair() is deprecated. Please use tls.Socket instead.
Error executing SQL query SELECT
cast(DB_Name(a.database_id) as varchar) as name,
    max(io_stall_read_ms),
    max(io_stall_write_ms),
    max(io_stall),
    max(io_stall_queued_read_ms),
    max(io_stall_queued_write_ms)
FROM
sys.dm_io_virtual_file_stats(null, null) a
INNER JOIN sys.master_files b ON a.database_id = b.database_id and a.file_id = b.file_id
group by a.database_id { RequestError: Invalid column name 'io_stall_queued_write_ms'.
    at RequestError (/usr/src/app/node_modules/tedious/lib/errors.js:34:12)
    at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:364:36)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:54:15)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at Parser.Readable.push (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:238:10)
  message: 'Invalid column name \'io_stall_queued_write_ms\'.',
  code: 'EREQUEST',
  number: 207,
  state: 1,
  class: 16,
  serverName: 'MSSQL-01',
  procName: '',
  lineNumber: 7 }

**Comment by awaragi** [comment]
Thank you for reporting this. What version of MSSQL are you running against?

**Comment by rowdy-fms** [comment]
I am getting the same error running against MSSQL 2012.

**Comment by awaragi** [comment]
Unfortunately, I have tested the queries with a later version of MSSQL. If you can fix the query to work with your version. I might be able to code in overrides for MSSQL12.

**Comment by rowdy-fms** [comment]
According to [Microsoft documentation](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-io-virtual-file-stats-transact-sql?view=sql-server-2017):

"io_stall_queued_read_ms | bigint | Does not apply to::  SQL Server 2008 through  SQL Server 2012 (11.x)." and "io_stall_queued_write_ms | bigint | Does not apply to::  SQL Server 2008 through  SQL Server 2012 (11.x)."

So these two metrics are simply not available for MSSQL versions 2012 and earlier.

The only way to fix the query is by removing those two metrics.
