### ISSUE TITLE
Exporter crashes with `ConnectionError: Connection lost - read ECONNRESET`

### ISSUE THREAD

**Issue by bluecmd** [awaragi/prometheus-mssql-exporter#26]
Running [this](https://hub.docker.com/layers/awaragi/prometheus-mssql-exporter/latest/images/sha256-3382588535b2aeb3cd3da8e89e8b62edf4fb8a4919407da8996b980822286baf?context=explore) version which is `:latest` at this time of writing.

If the connection is reset when the scrape is happening, the exporter crashes. Example log:
```
Tue, 06 Jul 2021 15:45:23 GMT app Connecting to database xyz-mssql

events.js:182
      throw er; // Unhandled 'error' event
      ^
ConnectionError: Connection lost - read ECONNRESET
    at ConnectionError (/usr/src/app/node_modules/tedious/lib/errors.js:12:12)
    at Connection.socketError (/usr/src/app/node_modules/tedious/lib/connection.js:703:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by cobolbaby** [comment]
Same as https://github.com/awaragi/prometheus-mssql-exporter/issues/10

**Comment by cobolbaby** [comment]
Same Question:

```
    | Sat, 05 Feb 2022 08:57:54 GMT app Connecting to database 10.99.106.95
    | Failed to connect to database: Failed to connect to 10.99.106.95:1433 in 15000ms
    | Sat, 05 Feb 2022 08:58:09 GMT app Connection to database ended
    | Sat, 05 Feb 2022 08:58:24 GMT app Connecting to database 10.99.106.95
    | 
    | events.js:352
    |       throw er; // Unhandled 'error' event
    |       ^
    | ConnectionError: Connection lost - connect ETIMEDOUT 10.99.106.95:1433
    |     at ConnectionError (/usr/src/app/node_modules/tedious/lib/errors.js:12:12)
    |     at Connection.socketError (/usr/src/app/node_modules/tedious/lib/connection.js:703:28)
    |     at /usr/src/app/node_modules/tedious/lib/connection.js:590:25
    |     at Socket.onError (/usr/src/app/node_modules/tedious/lib/connector.js:48:9)
    |     at Socket.emit (events.js:375:28)
    |     at emitErrorNT (internal/streams/destroy.js:106:8)
    |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
    | Emitted 'error' event on Connection instance at:
    |     at Connection.socketError (/usr/src/app/node_modules/tedious/lib/connection.js:703:14)
    |     at /usr/src/app/node_modules/tedious/lib/connection.js:590:25
    |     [... lines matching original stack trace ...]
    |     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    |   code: 'ESOCKET'
    | }
```

**Comment by awaragi** [comment]
tedious updated to latest 14.3.0 in version 1.1 coming up soon
