### ISSUE TITLE
Can we add any custom metrics? when i try to add I receive an error

### ISSUE THREAD

**Issue by karthikkulkarni1** [awaragi/prometheus-mssql-exporter#32]
Hi,

Great Exporter, as i was exploring to add a new metric i am receiving an error:

If i remove the added metric the error goes off. any advise?

(node:26873) [DEP0064] DeprecationWarning: tls.createSecurePair() is deprecated. Please use tls.Socket instead.
/var/mssql-prometheus/prometheus-mssql-exporter/metrics.js:21
        metrics.mssql_instance_name.set(mssql_instance_name);
                                    ^

TypeError: Cannot read property 'set' of undefined
    at Object.collect (/var/mssql-prometheus/prometheus-mssql-exporter/metrics.js:21:37)
    at Request [as userCallback] (/var/mssql-prometheus/prometheus-mssql-exporter/index.js:71:27)
    at Request._this.callback (/var/mssql-prometheus/prometheus-mssql-exporter/node_modules/tedious/lib/request.js:47:27)
    at Connection.message (/var/mssql-prometheus/prometheus-mssql-exporter/node_modules/tedious/lib/connection.js:1401:27)
    at Connection.dispatchEvent (/var/mssql-prometheus/prometheus-mssql-exporter/node_modules/tedious/lib/connection.js:687:45)
    at MessageIO.<anonymous> (/var/mssql-prometheus/prometheus-mssql-exporter/node_modules/tedious/lib/connection.js:602:18)
    at emitNone (events.js:106:13)
    at MessageIO.emit (events.js:208:7)
    at ReadablePacketStream.<anonymous> (/var/mssql-prometheus/prometheus-mssql-exporter/node_modules/tedious/lib/message-io.js:102:16)
    at emitOne (events.js:116:13)
events.js:208:7)
de: 'ETIMEOUT' }
Error executing SQL query SELECT DB_NAME(sP.dbid)
        , COUNT(sP.spid)
FROM sys.sysprocesses sP
GROUP BY DB_NAME(sP.dbid) { RequestError: Timeout: Request failed to complete in 15000ms
    at RequestError (/var/mssql-prometheus/prometheus-mssql-exporter/node_modules/tedious/lib/errors.js:34:12)
    at Connection.message (/var/mssql-prometheus/prometheus-mssql-exporter/node_modules/tedious/lib/connection.js:1431:40)

Thank you

**Comment by awaragi** [comment]
Can you please provide your modified code? not sure why you want to remove a metric? version 1.1 coming out soon will add few more metrics.
