### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by krislev** [awaragi/prometheus-mssql-exporter#37]
Hello,

Useful exporter , i just deployed 2  new MSSQL instances (2012 & 2019) and each exporters fails with :

_/usr/src/app/metrics.js:232

    const page_read = row[0].value;

                         ^

TypeError: Cannot read properties of undefined (reading '0')

    at Object.collect (/usr/src/app/metrics.js:232:26)

    at Request.userCallback (/usr/src/app/index.js:82:19)

    at Request.callback (/usr/src/app/node_modules/tedious/lib/request.js:205:14)

    at Parser.onEndOfMessage (/usr/src/app/node_modules/tedious/lib/connection.js:2854:22)

    at Object.onceWrapper (node:events:645:28)

    at Parser.emit (node:events:526:28)

    at Readable.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:32:12)

    at Readable.emit (node:events:526:28)

    at endReadableNT (node:internal/streams/readable:1345:12)

    at processTicksAndRejections (node:internal/process/task_queues:83:21)_

it seems that occurs after collecting database files size.
I try to put more rights to SQL login but no clue.

Any ideas ?

Regards,

Kristophe

**Comment by krislev** [comment]
Finally instead of use the latest : [v1.1.0](https://hub.docker.com/layers/prometheus-mssql-exporter/awaragi/prometheus-mssql-exporter/v1.1.0/images/sha256-83561227edf7fcefea098a8d7a70b55215bc0c0ef19a9cee18e8efbadac3eee1?context=explore) i use an oldest version [v1.0.1](https://hub.docker.com/layers/prometheus-mssql-exporter/awaragi/prometheus-mssql-exporter/v1.0.1/images/sha256-7d12ef75d314a5ac3a5bb2bc2ee212bd018fbf85282193d078256b4e930f5c0f?context=explore) and i works ! 
I just have an error for below query :
Error executing SQL query SELECT

cast(DB_Name(a.database_id) as varchar) as name,

    max(io_stall_read_ms),

    max(io_stall_write_ms),

    max(io_stall),

    max(io_stall_queued_read_ms),

    max(io_stall_queued_write_ms)

FROM

sys.dm_io_virtual_file_stats(null, null) a

INNER JOIN sys.master_files b ON a.database_id = b.database_id and a.file_id = b.file_id

group by a.database_id RequestError: Invalid column name 'io_stall_queued_write_ms'.

    at RequestError (/usr/src/app/node_modules/tedious/lib/errors.js:34:12)

    at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:364:36)

    at Parser.emit (node:events:526:28)

    at Parser.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:54:15)

    at Parser.emit (node:events:526:28)

    at addChunk (/usr/src/app/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:291:12)

    at readableAddChunk (/usr/src/app/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:278:11)

    at Parser.Readable.push (/usr/src/app/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:245:10)

    at Parser.Transform.push (/usr/src/app/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:148:32)

    at doneParsing (/usr/src/app/node_modules/tedious/lib/token/stream-parser.js:102:18) {

  code: 'EREQUEST',

  number: 207,

  state: 1,

  class: 16,

  serverName: 'LEVCOM-SRV\\D12GEN0',

  procName: '',

  lineNumber: 7

}
but the container did not stop again.

Regards,

Kristophe

**Comment by cobolbaby** [comment]
Please provide the specific version of the database, and execute the following SQL to view the response.

> _/usr/src/app/metrics.js:232

```sql
SELECT * FROM 
        (
            SELECT rtrim(counter_name) as counter_name, cntr_value
            FROM sys.dm_os_performance_counters
            WHERE counter_name in ('Page reads/sec', 'Page writes/sec', 'Page life expectancy', 'Lazy writes/sec', 'Checkpoint pages/sec')
            AND object_name = 'SQLServer:Buffer Manager'
        ) d
        PIVOT
        (
        MAX(cntr_value)
        FOR counter_name IN ([Page reads/sec], [Page writes/sec], [Page life expectancy], [Lazy writes/sec], [Checkpoint pages/sec])
        ) piv
```

> Error: Invalid column name 'io_stall_queued_write_ms'.

```
SELECT
cast(DB_Name(a.database_id) as varchar) as name,
    max(io_stall_read_ms),
    max(io_stall_write_ms),
    max(io_stall),
    max(io_stall_queued_read_ms),
    max(io_stall_queued_write_ms)
FROM
sys.dm_io_virtual_file_stats(null, null) a
INNER JOIN sys.master_files b ON a.database_id = b.database_id and a.file_id = b.file_id
GROUP BY a.database_id
```

Ps: Please reformat your issue content.

**Comment by awaragi** [comment]
@cobolbaby if I have a potential issue with a query, please I apprciate your help and a PR to fix it. 

I admit that my MSSQL admin skills are minimal and most of the queries here were donated by expert DB admins that I know and PRs from various users and forks.

**Comment by awaragi** [comment]
Version 1.2.0 is out and should be more robust in face of failed queries or queries that return no results
