### ISSUE TITLE
mssql-exporter crashes when trying to scrape data from Azure SQL

### ISSUE THREAD

**Issue by SergeyRim** [awaragi/prometheus-mssql-exporter#39]
Hello.

I'm trying to use this exporter to scrape data from Azure SQL server.
SQL Server version: Microsoft SQL Azure (RTM) - 12.0.2000.8 
I'm using admin account, so it should have all the required privileges.

Can you please help me to troubleshoot the issue?

Thanks.

Attaching the output:

```
2022-04-16T12:53:52.954Z app Prometheus-MSSQL Exporter listening on local port 4000 monitoring PDadmin@somecompany-development.database.windows.net:1433
2022-04-16T12:54:34.329Z app Received metrics request
2022-04-16T12:54:34.329Z db Connecting to database somecompany-development.database.windows.net using user PDadmin
          "name": "BigInt"
        },
        "colName": "cntr_value"
      }
    }
  ],
  [
    {
      "value": "master",
      "metadata": {
        "userType": 0,
        "flags": 33,
        "type": {
          "id": 231,
          "type": "NVARCHAR",
          "name": "NVarChar",
          "maximumLength": 4000
        },
        "collation": {
          "lcid": 1033,
          "flags": 13,
          "version": 0,
          "sortId": 52,
          "codepage": "CP1252"
        },
        "dataLength": 256,
        "colName": ""
      }
    },
    {
      "value": "2",
      "metadata": {
        "userType": 0,
        "flags": 8,
        "type": {
          "id": 127,
          "type": "INT8",
          "name": "BigInt"
        },
        "colName": "cntr_value"
      }
    }
  ]
]
2022-04-16T12:54:34.487Z metrics Fetched number log growths for database c21afb94-8777-409e-995e-b015f008ae99 0
2022-04-16T12:54:34.490Z metrics Fetched number log growths for database msdb 2
2022-04-16T12:54:34.490Z metrics Fetched number log growths for database tempdb 0
2022-04-16T12:54:34.490Z metrics Fetched number log growths for database model_masterdb 0
2022-04-16T12:54:34.490Z metrics Fetched number log growths for database model_userdb 0
2022-04-16T12:54:34.490Z metrics Fetched number log growths for database model 0
2022-04-16T12:54:34.490Z metrics Fetched number log growths for database mssqlsystemresource 0
2022-04-16T12:54:34.490Z metrics Fetched number log growths for database master 2
2022-04-16T12:54:34.490Z queries Executing query: SELECT DB_NAME(database_id) AS database_name, name AS logical_name, type, physical_name, (size * CAST(8 AS BIGINT)) size_kb FROM sys.master_files
Error executing SQL query SELECT DB_NAME(database_id) AS database_name, name AS logical_name, type, physical_name, (size * CAST(8 AS BIGINT)) size_kb FROM sys.master_files RequestError: Invalid object name 'sys.master_files'.
    at RequestTokenHandler.onErrorMessage (/usr/src/app/node_modules/tedious/lib/token/handler.js:360:21)
    at Readable.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:26:33)
    at Readable.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at next (node:internal/streams/from:98:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'EREQUEST',
  number: 208,
  state: 1,
  class: 16,
  serverName: 'somecompany-development',
  procName: '',
  lineNumber: 1
}
2022-04-16T12:54:34.497Z queries Executing query: 
        SELECT * FROM 
        (
            SELECT rtrim(counter_name) as counter_name, cntr_value
            FROM sys.dm_os_performance_counters
            WHERE counter_name in ('Page reads/sec', 'Page writes/sec', 'Page life expectancy', 'Lazy writes/sec', 'Checkpoint pages/sec')
            AND object_name = 'SQLServer:Buffer Manager'
        ) d
        PIVOT
        (
        MAX(cntr_value)
        FOR counter_name IN ([Page reads/sec], [Page writes/sec], [Page life expectancy], [Lazy writes/sec], [Checkpoint pages/sec])
        ) piv
    
2022-04-16T12:54:34.526Z queries Retrieved rows []
/usr/src/app/metrics.js:232
    const page_read = row[0].value;
                         ^

TypeError: Cannot read properties of undefined (reading '0')
    at Object.collect (/usr/src/app/metrics.js:232:26)
    at Request.userCallback (/usr/src/app/index.js:82:19)
    at Request.callback (/usr/src/app/node_modules/tedious/lib/request.js:205:14)
    at Parser.onEndOfMessage (/usr/src/app/node_modules/tedious/lib/connection.js:2854:22)
    at Object.onceWrapper (node:events:645:28)
    at Parser.emit (node:events:526:28)
    at Readable.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:32:12)
    at Readable.emit (node:events:526:28)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Stream closed EOF for monitoring/mssql-exporter-548df548c-j6lnq (mssql-exporter)
```

**Comment by SergeyRim** [comment]
Probably duplicate of https://github.com/awaragi/prometheus-mssql-exporter/issues/37
I have switched to version v1.0.1 and now it works (some queries still produces errors, but at least the container not crashing anymore).

**Comment by awaragi** [comment]
I am going to make the container more robust when a query returns 0 rows but I cannot test the queries itself as I do not have access to an Azure SQL server.

**Comment by awaragi** [comment]
Version 1.2.0 is out and should be more robust in face of failed queries or queries that return no results
