### ISSUE TITLE
1.2.1 some metrics cannot be gained

### ISSUE THREAD

**Issue by buddynotshotme** [awaragi/prometheus-mssql-exporter#41]
Q:mssql_product_version displays incorrectly.
expect：10.50.1600.1
in fact: mssql_product_version 15
----------------------------------------------
Q:Invalid column name 'database_id' ?
---------------------------------------------
Q: Get  the value 'database_id' dynamically.
tip:
get current databse_id:
select dbid from master..sysprocesses where spid=@@spid

This err  causes the following problems.
---------------------------------------------
metric mssql_client_connections
metric mssql_io_stall
-----------------------------------------
Error executing metric mssql_client_connections SQL query SELECT host_name, DB_NAME(database_id), COUNT(*)
FROM sys.dm_exec_sessions
WHERE is_user_process=1
GROUP BY host_name, database_id RequestError: Invalid column name 'database_id'.
    at RequestTokenHandler.onErrorMessage (/usr/src/app/node_modules/tedious/lib/token/handler.js:360:21)
    at Readable.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:26:33)
    at Readable.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at next (node:internal/streams/from:98:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'EREQUEST',
  number: 207,
  state: 1,
  class: 16,
  serverName: 'STANDBY',
  procName: '',
  lineNumber: 1
}
Error executing metric mssql_io_stall SQL query SELECT
cast(DB_Name(a.database_id) as varchar) as name,
    max(io_stall_read_ms),
    max(io_stall_write_ms),
    max(io_stall),
    max(io_stall_queued_read_ms),
    max(io_stall_queued_write_ms)
FROM
sys.dm_io_virtual_file_stats(null, null) a
INNER JOIN sys.master_files b ON a.database_id = b.database_id and a.file_id = b.file_id
GROUP BY a.database_id RequestError: Invalid column name 'io_stall_queued_write_ms'.
    at RequestTokenHandler.onErrorMessage (/usr/src/app/node_modules/tedious/lib/token/handler.js:360:21)
    at Readable.<anonymous> (/usr/src/app/node_modules/tedious/lib/token/token-stream-parser.js:26:33)
    at Readable.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at next (node:internal/streams/from:98:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'EREQUEST',
  number: 207,
  state: 1,
  class: 16,
  serverName: 'STANDBY',
  procName: '',
  lineNumber: 7
}

**Comment by buddynotshotme** [comment]
well,the root cause is that some fields do not exist or do not apply to SQL Server 2008.
my solution about "mssql_client_connections hasn't the "database_id" field" is
            SELECT host_name, DB_NAME(dbid) dbname, COUNT(*) session_count
            FROM sys.dm_exec_sessions a 
            LEFT JOIN
            sysprocesses b
            on a.session_id=b.spid
            WHERE is_user_process=1
            GROUP BY host_name, dbid
========================
but "mssql_io_stall" ,hava any idea?
<img width="487" alt="1" src="https://user-images.githubusercontent.com/32627869/165465676-7da58160-a7b0-4a33-8179-c600b0c6c993.png">

quote：
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-io-virtual-file-stats-transact-sql?view=sql-server-ver15
===================
it seems like a bug in mssql_product_version.  
mssql_product_version is a Numerical type now.  
  const mssql_product_version = v.major + v.minor / 10
  edit:
  const mssql_product_version = v.major +"."+ v.minor
@awaragi

**Comment by awaragi** [comment]
Thanks for the detailed info. I will try to fix it very quickly.

Is the container still up at least and the remainder of metrics are working?

**Comment by awaragi** [comment]
I have updated the version computation and replaced the query for connections with your suggested one. I've also added more error handling which should keep the container from crashing on failed metric. So you will get all metrics except the stall one (I admit I have no fix for it).

See https://github.com/awaragi/prometheus-mssql-exporter/releases/tag/v1.3.0
